var members = {
    'Advisors': [
        {
            name: '張俊盛',
        },
    ],
    'Ph.D. Students': [
        {
            name: 'Joanne Boisson',
            alias: '喬安娜',
        },
        {
            name: '陳志杰',
            alias: 'jjc',
        },
    ],
    'Research Assistants': [
        {
            name: '彭皓鈞',
            alias: 'Henry',
        },
    ],
    'Master Students': [
        {
            name: '葉玫慈',
            alias: 'Mei-Cih',
            research: 'Automatic Paraphrases Generation',
            img: 'img/meichi.jpg',
            bkg_color: '#DC143C',
            intro: 'Ukulele是人生的一半(\'A`)',
            link: 'https://youtu.be/z2Xsp0HMqf8',
        },
        {
            name: '陳怡君',
            alias: 'Yi-Chun',
            research: '機器翻譯、同步樣式文法',
            img: 'img/chun.jpg',
            bkg_color: '#EE7600',
            intro: '半夜睡不著覺，把心情哼成歌',
            link: 'https://youtu.be/O9cvAQEzG0o',
        },
        {
            name: '陳鵬宇',
            alias: 'Peng-Yu',
            research: '文法改錯',
            img: 'img/pengyu.jpg',
            bkg_color: '#CDCD00',
            intro: '太極拳法掌門人',
            link: 'https://youtu.be/wr-6wwt8RXk',
        },
        {
            name: '黃婕雅',
            alias: 'jr',
            research: 'Automatic Paraphrases Generation',
            img: 'img/jr.jpg',
            bkg_color: '#008B45',
            intro: '只是你遲到一千年！',
            link: 'https://youtu.be/83TjxZWFXVI',
        },
        {
            name: '吳瑀瑄',
            alias: 'shanny',
            research: '英文文法（動詞）偵錯與改錯',
            img: 'img/shanny.jpg',
            bkg_color: '#473C8B',
            intro: '看到我請提醒我記得帶電源線和學生證 (￣３￣)a',
            link: 'https://youtu.be/Xn676-fLq7I',
        },
        {
            name: '吳奇恩',
            alias: 'Tony',
            research: '機器翻譯',
            img: 'img/57n.jpg',
            bkg_color: '#141414',
            intro: '57n',
            link: 'https://youtu.be/hgGFe4eJ0qc',
        },
        {
            name: '杜惟真',
            alias: 'Jane',
            research: '英語檢定輔助系統、動詞型態改錯',
            img: 'img/jane.jpg',
            bkg_color: '#EEAD0E',
            intro: '呵呵呵 好哦',
            link: 'https://youtu.be/7sbKm-hAlsw',
        },
        {
            name: '羅右鈞',
            alias: 'Howard Lo',
            research: 'Deep Learning for NLP <3',
            img: 'img/howard.jpeg',
            bkg_color: '#0d5b3c',
            intro: '在不斷的掙扎天空出現一道彩虹，在不斷的懷疑之後找到原來的我。',
            link: 'https://www.youtube.com/watch?v=pbLJxFBOs80'
        },
        {
            name: '李巧雯',
            alias: 'ChiaoWen',
            research: '',
            img: 'img/chiaowen.jpg',
            bkg_color: '#f48a6e',
            intro: '顆顆顆',
            link: 'https://www.youtube.com/watch?v=iq_d8VSM0nw',
        },
        {
            name: '林昌毅',
            alias: 'Chungyilin',
            research: '5 4 tusi be ba',
            img: 'img/chungyilin.jpg',
            bkg_color: '#EEAD0E',
            intro: '故人西辭黃鶴樓，煙花三月下揚州。 孤帆遠影碧空盡，唯見長江天際流。',
            link: 'https://www.youtube.com/watch?v=HSHOU1OVbaY',
        },
    ],
    'Undergraduates': [
        {
            name: '朱凰華',
            alias: 'Garnix',
            research: 'Email寫作輔助',
        },
        {
            name: '徐芷翎',
            alias: 'Amy',
            research: 'Email寫作輔助',
        },
        {
            name: '簡紹安',
            alias: 'Shao-An',
            research: '自然語言搜尋介面',
        },
        {
            name: '蔡明勳',
            alias: 'Frank',
            research: '自然語言搜尋介面',
        },
    ],
};
