var members = {
    'boss': [
        {
            name: '楊謦瑜',
            alias: 'Helen',
            research: '#',
            img: 'img/helen.jpg',
            color: 'red',
            intro: '#',
            link: '#',
        },
    ],
    'phd-students': [
        {
            name: 'Joanne Boisson',
            alias: '喬安娜',
            research: '#',
            img: 'img/joanne.jpg',
            color: 'red',
            intro: '#',
            link: '#',
        },
        {
            name: '陳志杰',
            alias: 'jjc',
            research: 'Machine Translation',
            img: 'img/jjc.jpg',
            color: 'black',
            intro: '我是胖虎我是孩子王',
            link: 'https://dspp779.github.io',
        },
    ],
    'ra': [
        {
            name: '彭晧鈞',
            alias: 'Henry',
            research: '',
            img: 'img/henry.jpg',
            color: 'blue',
            intro: '',
            link: '',
        },
    ],
    'ms-students': [
        // {
        //    name: '葉玫慈',
        //    alias: 'Mei-Cih',
        //    research: 'Automatic Paraphrases Generation',
        //    img: 'img/meichi.jpg',
        //    color: 'red',
        //    intro: 'Ukulele是人生的一半(\'A`)',
        //    link: 'https://youtu.be/z2Xsp0HMqf8',
        // },
        // {
        //     name: '陳怡君',
        //     alias: 'Yi-Chun',
        //     research: '機器翻譯、同步樣式文法',
        //     img: 'img/chun.jpg',
        //     color: 'orange',
        //     intro: '半夜睡不著覺，把心情哼成歌',
        //     link: 'https://youtu.be/O9cvAQEzG0o',
        // },
        // {
        //     name: '陳鵬宇',
        //     alias: 'Peng-Yu',
        //     research: '文法改錯',
        //     img: 'img/pengyu.jpg',
        //     color: 'yellow',
        //     intro: '太極拳法掌門人',
        //     link: 'https://youtu.be/wr-6wwt8RXk',
        // },
        // {
        //     name: '黃婕雅',
        //     alias: 'jr',
        //     research: 'Automatic Paraphrases Generation',
        //     img: 'img/jr.jpg',
        //     color: 'green',
        //     intro: '只是你遲到一千年！',
        //     link: 'https://youtu.be/83TjxZWFXVI',
        // },
        // {
        //     name: '吳奇恩',
        //     alias: 'Tony',
        //     research: '機器翻譯',
        //     img: 'img/57n.jpg',
        //     color: 'teal',
        //     intro: '57n',
        //     link: 'https://youtu.be/hgGFe4eJ0qc',
        // },
        // {
        //     name: '杜惟真',
        //     alias: 'Jane',
        //     research: '英語檢定輔助系統、動詞型態改錯',
        //     img: 'img/jane.jpg',
        //     color: 'blue',
        //     intro: '呵呵呵 好哦',
        //     link: 'https://youtu.be/7sbKm-hAlsw',
        // },
        // {
        //     name: '吳瑀瑄',
        //     alias: 'shanny',
        //     research: '自動文法改錯',
        //     img: 'img/shanny.jpg',
        //     color: 'violet',
        //     intro: '走啊，跑步！',
        //     link: 'https://youtu.be/m99Py_8NtZE',
        // },
        {
            name: '羅右鈞',
            alias: 'Howard Lo',
            research: 'Deep Learning for NLP <3',
            img: 'img/howard.jpeg',
            color: 'brown',
            intro: '在不斷的掙扎天空出現一道彩虹，在不斷的懷疑之後找到原來的我。',
            link: 'https://www.youtube.com/watch?v=pbLJxFBOs80'
        },
        {
            name: '李巧雯',
            alias: 'ChiaoWen',
            research: '#',
            img: 'img/chiaowen.jpg',
            color: 'pink',
            intro: '顆顆顆',
            link: 'https://www.youtube.com/watch?v=iq_d8VSM0nw',
        },
        {
            name: '林昌毅',
            alias: 'Chungyilin',
            research: '5 4 tusi be ba',
            img: 'img/chungyilin.jpg',
            color: 'grey',
            intro: '故人西辭黃鶴樓，煙花三月下揚州<br />孤帆遠影碧空盡，唯見長江天際流。',
            link: 'https://www.youtube.com/watch?v=HSHOU1OVbaY',
        },
        //
        {
            name: '程尚謙',
            alias: 'Ashley',
            research: '#',
            img: 'img/ashley.jpg',
            color: 'olive',
            intro: 'XDDDD',
            link: '#',
        },
       
        
        {
            name: '朱凰華',
            alias: 'Garnix',
            research: '#',
            img: 'img/garnix.jpg',
            color: 'red',
            intro: '無敵艦隊碾壓世界<br> <br>信妙芳得永生<br>↘',
            link: 'https://www.youtube.com/watch?v=fTYgpGdvFa4',
        },
        
        {
            name: '蔡仲庭',
            alias: 'Ting',
            research: '#',
            img: 'img/ting.jpg',
            color: 'red',
            intro: '在看我嗎？<br> <br>信妙芳得永生<br>↓',
            link: 'https://www.facebook.com/%E5%A6%99%E8%8A%B3%E5%A4%A7%E5%B8%AB-134564827164423/?ref=br_rs',
        },
        {
            name: '謝毅霖',
            alias: 'Charles',
            research: '#',
            img: 'img/yee0.jpg',
            color: 'yellow',
            intro: '矮額 偷看我喔<br><br>信妙芳得永生<br>↙',
            link: 'https://www.youtube.com/watch?v=1nv9br7P7g0',
        },
        {
            name: '彭成全',
            alias: 'Zeno',
            research: '#',
            img: 'img/zeno.jpg',
            color: 'black',
            intro: 'なに',
            link: 'https://www.youtube.com/watch?v=HAIDqt2aUek',
        },
        
        {
            name: '韓文彬',
            alias: 'Vincent',
            research: '#',
            img: 'img/vincent.jpg',
            color: 'red',
            intro: '最初的感動<br><br>信妙芳得永生<br>→',
            link: 'https://www.youtube.com/watch?v=Bjz9VIHTDmo&list=PL68601D29FD1E293F',
        },
        {
            name: '何佳芳',
            alias: 'Seafood',
            research: '#',
            img: 'img/fun.jpg',
            color: 'red',
            intro: '我愛獨角獸查理',
            link: 'https://www.youtube.com/watch?v=cMOHAcjlIWs',
        },
        //
        
        {
            name: '蔡名喬',
            alias: 'Mictsai',
            research: '#',
            img: 'img/Mictsai.jpg',
            color: 'red',
            intro: '宅錯了嗎<br><br>信妙芳得永生<br>←',
            link: '',
        },
    ],
    'undergraduates': [
        {
            name: '賴怡惠',
            alias: 'Irene',
            research: '#',
            img: 'img/irene.jpg',
            color: 'red',
            intro: '',
            link: '',
        },
        {
            name: '陳映竹',
            alias: 'Jocelyn',
            research: '#',
            img: 'img/jocelyn.jpg',
            color: 'red',
            intro: '',
            link: '',
        },

        // {
        //     name: '徐芷翎',
        //     alias: 'Amy',
        //     research: 'Email寫作輔助',
        //     img: 'img/amy.jpg',
        //     color: 'orange',
        //     intro: '',
        //     link: '',
        // },
        // {
        //     name: '簡紹安',
        //     alias: 'Shao-An',
        //     research: '自然語言搜尋介面',
        //     img: 'img/shaoan.jpg',
        //     color: 'yellow',
        //     intro: '',
        //     link: '',
        // },
        // {
        //     name: '蔡明勳',
        //     alias: 'Frank',
        //     research: '自然語言搜尋介面',
        //     img: 'img/frank.jpg',
        //     color: 'green',
        //     intro: '',
        //     link: '',
        // },
    ],
};
